# Generated by Django 3.2.7 on 2021-10-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataretrievalapi', '0002_auto_20210930_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recipes',
        ),
        migrations.AddField(
            model_name='step',
            name='orderNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataretrievalapi.recipe'),
            preserve_default=False,
        ),
    ]
