# Generated by Django 3.2.7 on 2021-10-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataretrievalapi', '0003_auto_20211001_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='orderNumber',
            new_name='orderValue',
        ),
    ]
